export enum TimelineEventType {
  HEALTH_RECORD_ADDED = 'HEALTH_RECORD_ADDED',
  WELLNESS_CHECK_IN = 'WELLNESS_CHECK_IN',
  CONSULTATION = 'CONSULTATION',
  APPOINTMENT = 'APPOINTMENT',
  OTHER = 'OTHER',
}
