export enum VerificationDocumentType {
  MEDICAL_LICENSE = 'MEDICAL_LICENSE',
  DEGREE_CERTIFICATE = 'DEGREE_CERTIFICATE',
  GOVERNMENT_ID = 'GOVERNMENT_ID',
  MALPRACTICE_INSURANCE = 'MALPRACTICE_INSURANCE',
  OTHER = 'OTHER',
}
