export enum NotificationType {
  APPOINTMENT_REQUESTED = 'APPOINTMENT_REQUESTED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_DECLINED = 'APPOINTMENT_DECLINED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  WAITLIST_OFFER = 'WAITLIST_OFFER',
  WAITLIST_EXPIRED = 'WAITLIST_EXPIRED',
  WAITLIST_FULFILLED = 'WAITLIST_FULFILLED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUND_PROCESSING = 'REFUND_PROCESSING',
  REFUND_COMPLETED = 'REFUND_COMPLETED',
  REFUND_FAILED = 'REFUND_FAILED',
  DOCTOR_VERIFICATION_SUBMITTED = 'DOCTOR_VERIFICATION_SUBMITTED',
  DOCTOR_VERIFICATION_APPROVED = 'DOCTOR_VERIFICATION_APPROVED',
  DOCTOR_VERIFICATION_REJECTED = 'DOCTOR_VERIFICATION_REJECTED',
  SECURITY_LOGIN = 'SECURITY_LOGIN',
  SECURITY_PASSWORD_CHANGED = 'SECURITY_PASSWORD_CHANGED',
  SECURITY_SESSION_REVOKED = 'SECURITY_SESSION_REVOKED',
  WELLNESS_REMINDER = 'WELLNESS_REMINDER',
  FOLLOW_UP_REMINDER = 'FOLLOW_UP_REMINDER',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  PUSH = 'PUSH',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}

export enum NotificationSeverity {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum DevicePlatform {
  ANDROID = 'ANDROID',
  IOS = 'IOS',
  WEB = 'WEB',
}
