export const AI_PROVIDER = Symbol('AI_PROVIDER');
export const AI_REPOSITORY = Symbol('AI_REPOSITORY');
export const AI_CONVERSATION_REPOSITORY = Symbol('AI_CONVERSATION_REPOSITORY');
export const AI_MESSAGE_REPOSITORY = Symbol('AI_MESSAGE_REPOSITORY');
export const AI_FEEDBACK_REPOSITORY = Symbol('AI_FEEDBACK_REPOSITORY');
export const AI_AUDIT_SERVICE = Symbol('AI_AUDIT_SERVICE');

// Phase 16 & 17 Tokens
export const SAFETY_CLASSIFIER = Symbol('SAFETY_CLASSIFIER');
export const MEDICAL_RETRIEVER = Symbol('MEDICAL_RETRIEVER');
export const REALTIME_AI_PROVIDER = Symbol('REALTIME_AI_PROVIDER');
