export * from './create-appointment.dto.js';
export * from './reserve-slot.dto.js';
export * from './appointment-response.dto.js';
export * from './cancel-appointment.dto.js';
export * from './decline-appointment.dto.js';
export * from './appointment-query.dto.js';
export * from './pre-consultation-draft.dto.js';
export * from './pre-consultation-response.dto.js';
export * from './cancellation-response.dto.js';
