import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { AIMessageRole } from '../enums/ai-message-role.enum.js';
import { AIMessageStatus } from '../enums/ai-message-status.enum.js';
import { AIConversationResponseDto } from './ai-conversation-response.dto.js';

export class AIMessageGenerationMetadataDto {
  @ApiProperty({
    description: 'AI model provider identifier',
    example: 'MOCK_PROVIDER',
  })
  public provider!: string;

  @ApiProperty({
    description: 'Underlying model version or designation',
    example: 'mock-companion-v1',
  })
  public model!: string;

  @ApiProperty({
    description: 'Inference response round-trip latency in milliseconds',
    example: 45,
  })
  public latencyMs!: number;

  @ApiProperty({
    description: 'Estimated prompt/input tokens',
    example: 120,
  })
  public promptTokens!: number;

  @ApiProperty({
    description: 'Estimated completion/output tokens',
    example: 65,
  })
  public completionTokens!: number;

  @ApiProperty({
    description: 'Total tokens processed',
    example: 185,
  })
  public totalTokens!: number;

  @ApiPropertyOptional({
    description: 'Generation stop reason',
    nullable: true,
    example: 'stop',
  })
  public finishReason?: string | null | undefined;

  @ApiPropertyOptional({
    description: 'Correlation or request tracing identifier',
    nullable: true,
    example: 'req-corr-987654',
  })
  public correlationId?: string | null | undefined;

  @ApiProperty({
    description: 'Explicit indicator affirming this message is AI-generated',
    example: true,
  })
  public isAiGenerated!: boolean;

  @ApiProperty({
    description: 'Non-clinical healthcare disclosure notice',
    example:
      'MANVIA AI Companion provides health and wellness information for educational and informational purposes only. It is not a doctor, cannot provide clinical diagnosis, and cannot prescribe medication.',
  })
  public disclosureNotice!: string;
}

export class AICitationDto {
  @ApiProperty({
    description: 'Knowledge source identifier',
    example: 'SRC-AHA2024',
  })
  public sourceId!: string;

  @ApiProperty({
    description: 'Title of medical guideline or reference document',
    example: 'Guidelines for the Prevention and Management of High Blood Pressure',
  })
  public title!: string;

  @ApiProperty({
    description: 'Issuing medical organization or health authority',
    example: 'American Heart Association / ACC',
  })
  public organization!: string;

  @ApiProperty({
    description: 'Unique document identifier',
    example: 'DOC-AHA-HTN-2024',
  })
  public documentId!: string;

  @ApiProperty({
    description: 'Relevance score computed during evidence retrieval',
    example: 0.94,
  })
  public relevance!: number;

  @ApiProperty({
    description: 'Factual evidence snippet used in response generation',
    example:
      'Normal adult blood pressure is defined as systolic < 120 mm Hg and diastolic < 80 mm Hg.',
  })
  public snippet!: string;
}

export class AIMessageResponseDto {
  @ApiProperty({
    description: 'Internal system message identifier (UUID)',
    example: '4f89d311-b924-41d5-bc4e-28f41e57c610',
  })
  public id!: string;

  @ApiProperty({
    description: 'Client-facing non-sequential message identifier',
    example: 'AIM-4T6M8P9Q',
  })
  public publicMessageId!: string;

  @ApiProperty({
    description: 'Conversation identifier this message belongs to',
    example: '8a95d712-421b-4fa8-9e67-d86ea529bfa1',
  })
  public conversationId!: string;

  @ApiProperty({
    description: 'Role of the message author',
    enum: AIMessageRole,
    example: AIMessageRole.ASSISTANT,
  })
  public role!: AIMessageRole;

  @ApiProperty({
    description: 'Message content text',
    example: 'Hello! I am your MANVIA AI Companion. How can I support your wellness today?',
  })
  public content!: string;

  @ApiProperty({
    description: 'Delivery/persistence status of the message',
    enum: AIMessageStatus,
    example: AIMessageStatus.DELIVERED,
  })
  public status!: AIMessageStatus;

  @ApiProperty({
    description: 'Affirmative flag indicating whether this message was generated by AI',
    example: true,
  })
  public isAiGenerated!: boolean;

  @ApiPropertyOptional({
    description: 'AI model generation metadata (tokens, latency, finish reason, provider)',
    type: AIMessageGenerationMetadataDto,
    nullable: true,
  })
  public generation?: AIMessageGenerationMetadataDto | null | undefined;

  @ApiPropertyOptional({
    description: 'Structured medical evidence citations retrieved via Medical RAG',
    type: [AICitationDto],
    nullable: true,
  })
  public citations?: AICitationDto[] | null | undefined;

  @ApiProperty({
    description: 'Message creation timestamp',
    example: '2026-09-29T21:00:00.000Z',
  })
  public createdAt!: string;

  @ApiProperty({
    description: 'Message last update timestamp',
    example: '2026-09-29T21:00:00.000Z',
  })
  public updatedAt!: string;
}

export class SendAIMessageResponseDto {
  @ApiProperty({
    description: 'The persisted user message',
    type: AIMessageResponseDto,
  })
  public userMessage!: AIMessageResponseDto;

  @ApiProperty({
    description: 'The generated AI companion assistant response',
    type: AIMessageResponseDto,
  })
  public assistantMessage!: AIMessageResponseDto;

  @ApiPropertyOptional({
    description: 'Indicates whether medical evidence context was retrieved and used',
    example: true,
  })
  public medicalContextUsed?: boolean | undefined;

  @ApiPropertyOptional({
    description: 'Citations for medical evidence utilized in generation',
    type: [AICitationDto],
  })
  public citations?: AICitationDto[] | undefined;

  @ApiPropertyOptional({
    description: 'Safety classification assigned during pre/post-checks',
    example: 'MEDICAL_INFORMATION',
  })
  public safetyClassification?: string | undefined;

  @ApiPropertyOptional({
    description: 'Action taken by the AI safety layer',
    example: 'DISCLOSURE_ATTACHED',
  })
  public safetyAction?: string | undefined;
}

export class AIConversationDetailResponseDto {
  @ApiProperty({
    description: 'Conversation session details',
    type: AIConversationResponseDto,
  })
  public conversation!: AIConversationResponseDto;

  @ApiProperty({
    description: 'Chronological message history for this conversation',
    type: [AIMessageResponseDto],
  })
  public messages!: AIMessageResponseDto[];
}
